---
abstract: 'Kelp with extra sweeteners'
author:
  - unknown
build_requires:
  DBIx::Class: '0'
  ExtUtils::MakeMaker: '0'
  Kelp::Module::Template::Toolkit: '0'
  Kelp::Test: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: KelpX-Sweet
no_index:
  directory:
    - t
    - inc
requires:
  Kelp: '0'
  Module::Find: '0'
  Moo: '0'
  Text::ASCIITable: '0'
  'true': '0'
version: '0.003'
